# Generated by Django 5.1.6 on 2025-02-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsor', '0001_initial'),
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_universitet', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя учебного заведения')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ф.И.О')),
                ('type_of_student', models.CharField(blank=True, choices=[('Kolledj', 'Kolledj'), ('Bakalavr', 'Bakalavr'), ('Magistratura', 'Magistratura')], max_length=200, null=True, verbose_name='Тип обучения')),
                ('sum_contract', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма контракта')),
                ('sponsors', models.ManyToManyField(related_name='students', through='sponsorship.Sponsorship', to='sponsor.sponsor', verbose_name='Спонсоры')),
                ('universitet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.universitet', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
