# Generated by Django 5.1.6 on 2025-02-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universitet',
            new_name='OTM',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='universitet',
            new_name='otm',
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Телефон номер'),
        ),
    ]
