# Generated by Django 5.1.6 on 2025-02-07 10:12

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_universitet_otm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[students.models.validate_phone_length], verbose_name='Телефон номер'),
        ),
    ]
