# Generated by Django 5.1.6 on 2025-02-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.otm', verbose_name='Учебное заведение'),
        ),
    ]
