# Generated by Django 5.1.6 on 2025-02-08 06:21

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_alter_sponsor_date_alter_sponsor_sponsorship_and_more'),
        ('sponsorship', '0004_remove_sponsorship_actions_remove_sponsorship_status'),
        ('students', '0005_alter_student_otm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True, validators=[students.models.validate_phone_length], verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='student',
            name='type_of_student',
            field=models.CharField(blank=True, choices=[('Kolledj', 'Kolledj'), ('Bakalavr', 'Bakalavr'), ('Magistratura', 'Magistratura')], db_index=True, max_length=200, null=True, verbose_name='Тип обучения'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone'], name='students_st_phone_86fc06_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['otm'], name='students_st_otm_id_e778b0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['type_of_student'], name='students_st_type_of_2445fe_idx'),
        ),
    ]
