# Generated by Django 5.1.6 on 2025-02-07 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ф.И.О')),
                ('phone', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Телефон номер')),
                ('sponsorship', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма спонсора')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Потраченная сумма')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sponsor_type', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], default='Jismoniy shaxs', max_length=15)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
