# Generated by Django 5.1.6 on 2025-02-07 10:12

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_remove_sponsor_amount_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('Barchasi', 'Barchasi'), ('Yangi', 'Yangi'), ('Moderatsiyada', 'Moderatsiyada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[students.models.validate_phone_length], verbose_name='Телефон номер'),
        ),
    ]
