# Generated by Django 5.1.6 on 2025-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_sponsor_type_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiyada', 'Moderatsiyada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=100, verbose_name='Статус'),
        ),
    ]
