# Generated by Django 5.1.6 on 2025-02-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_initial'),
        ('students', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='students.student', verbose_name='Студент'),
        ),
    ]
