# Generated by Django 5.1.6 on 2025-02-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_alter_sponsorship_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='status',
        ),
    ]
